### ISSUE TITLE
Spotifyの実行ファイルパス取得に失敗する（ユーザー名とユーザーフォルダが異なる場合）

### ISSUE THREAD

**Issue by ThinaticSystem** [Sagiri-Dev/Sagiri#10]
Misskeyに流れてきてなんとなく動かしてみたところ起動できなかったので一応報告だけさせていただきます。

## 不具合内容

起動時にSpotifyの実行パスの取得に失敗します

ユーザー名とユーザーフォルダが異なる場合（Microsoftアカウントで登録した場合など？）に\
Spotify.exeの実行時に存在しないパスを参照してしまうようです

![image](https://github.com/Sagiri-Dev/Sagiri/assets/37925599/2c6df25a-769e-4997-8d62-a8af3ae4d323)

ユーザー名（`/しなちくシステム/`）でパスが指定されていますが\
私の環境で実際のユーザーフォルダの名前はそうではなくoutlookのアドレスの先頭5文字になっています（はずかしい）

## 解決案

C#何もわかりませんが軽く調べたところ\
この部分で現在の実装だと`Environment.UserName`を受け取りパスを指定していますが\
カレントユーザーのRomingディレクトリを指定する目的だと\
`Environment.SpecialFolder.ApplicationData`等を使うと良さそう？な感じです\
ほんまか\
cf. https://learn.microsoft.com/ja-jp/dotnet/api/system.environment.specialfolder?view=net-7.0
https://github.com/Sagiri-Dev/Sagiri/blob/fb8ff99f7886f074497a42d70d3801e4295ab834/Sagiri/Util/Common/Constants.cs#L21-L22

**Comment by Asteriskx** [comment]
報告ありがとうございます。
Windows 側、この辺が雰囲気になってるので辛いところですね。
ちょっと直してみます。

**Comment by Asteriskx** [comment]
このアプリとしては、起動前提で動いてもらうものなので、
起動チェックをなくしました(それでいいのか問題はありますが...)

この後リリースします！
